nome=input('Digite um funcionario: ')
empresa=input('Digite a instituicao: ')
qtde_funcionarios=int(input('digite a qtde de funcionarios: '))
mediaMensalidade=float(input('Digite a media da mensalidade: '))
print(nome + ' trabalha na empresa ' + empresa)
print('Possui: ', qtde_funcionarios, ' funcionarios')
print('A media da mensalidade e de: ' +str(mediaMensalidade))
print("==============Verifique os tipos de dados abaixo:==============")
print("O tipo de dado da variavel [nome] é: ",type(nome))
print("O tipo de dado da variavel [empresa] é: ",type(empresa))
print("O tipo de dado da variavel [qtde_funcionarios] é: ",type(qtde_funcionarios))
print("O tipo de dado da variavel [mediaMensalidade] é: ",type(mediaMensalidade))