nome=input('Digite um funcionario: ')
empresa=input('Digite a instituicao: ')
qtde_funcionarios=int(input('digite a qtde de funcionarios: '))
mediaMensalidade=float(input('Digite a media da mensalidade: '))
print(nome + ' trabalha na empresa ' + empresa)
print('Possui: ', qtde_funcionarios, ' funcionarios')
print('A media da mensalidade e de: ' +str(mediaMensalidade))